# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_LH.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GNSSAzElWindow(object):
    def setupUi(self, GNSSAzElWindow):
        GNSSAzElWindow.setObjectName("GNSSAzElWindow")
        GNSSAzElWindow.resize(650, 650)
        self.centralwidget = QtWidgets.QWidget(GNSSAzElWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(550, 0, 91, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_close = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 0, 351, 24))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxGPS = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxGPS.setAcceptDrops(False)
        self.checkBoxGPS.setChecked(True)
        self.checkBoxGPS.setObjectName("checkBoxGPS")
        self.horizontalLayout_2.addWidget(self.checkBoxGPS)
        self.checkBoxGLONASS = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxGLONASS.setChecked(True)
        self.checkBoxGLONASS.setObjectName("checkBoxGLONASS")
        self.horizontalLayout_2.addWidget(self.checkBoxGLONASS)
        self.checkBoxGALILEO = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxGALILEO.setChecked(True)
        self.checkBoxGALILEO.setObjectName("checkBoxGALILEO")
        self.horizontalLayout_2.addWidget(self.checkBoxGALILEO)
        self.checkBoxBEIDOU = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxBEIDOU.setChecked(True)
        self.checkBoxBEIDOU.setObjectName("checkBoxBEIDOU")
        self.horizontalLayout_2.addWidget(self.checkBoxBEIDOU)
        GNSSAzElWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GNSSAzElWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 25))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        GNSSAzElWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(GNSSAzElWindow)
        self.statusBar.setObjectName("statusBar")
        GNSSAzElWindow.setStatusBar(self.statusBar)
        self.file_menu.addSeparator()
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(GNSSAzElWindow)
        QtCore.QMetaObject.connectSlotsByName(GNSSAzElWindow)

    def retranslateUi(self, GNSSAzElWindow):
        _translate = QtCore.QCoreApplication.translate
        GNSSAzElWindow.setWindowTitle(_translate("GNSSAzElWindow", "GNSS Azimuth-Elevation View"))
        self.btn_close.setText(_translate("GNSSAzElWindow", "Close"))
        self.checkBoxGPS.setText(_translate("GNSSAzElWindow", "GPS"))
        self.checkBoxGLONASS.setText(_translate("GNSSAzElWindow", "GLONASS"))
        self.checkBoxGALILEO.setText(_translate("GNSSAzElWindow", "GALILEO"))
        self.checkBoxBEIDOU.setText(_translate("GNSSAzElWindow", "BEIDOU"))
        self.file_menu.setTitle(_translate("GNSSAzElWindow", "File"))
        self.help_menu.setTitle(_translate("GNSSAzElWindow", "Help"))
